# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: perpetualpossum
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: snowalerts-tc-discord
# "service" is the name of this project. This will also be added to your AWS resource names.
service: snowalerts-tc-discord

stages:
  default:
    params:
      subscribedChannelsTableName: "subscribed-channels-${sls:stage}"
      smsMessagesTableName: "sms-messages-${sls:stage}"
      proccessedNotificationsTableName: "proccessed-notifications-${sls:stage}"
    resolvers:
      doppler:
        type: doppler
        token: ${env:DOPPLER_TOKEN}
        project: snowalerts-tc-discord
        config: dev

  prod:
    resolvers:
      doppler:
        type: doppler
        token: ${env:DOPPLER_TOKEN}
        project: snowalerts-tc-discord
        config: prod

plugins:
  - serverless-lift

custom:
  pythonRequirements:
    dockerizePip: true
    useUv: true
    installer: uv

package:
  include:
    - '!./**'
    - './src/**'
  exclude:
    - '**'

provider:
  name: aws
  runtime: python3.13
  architecture: arm64
  region: ${env:AWS_DEFAULT_REGION}
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ProccessedNotificationsTable, Arn]
            - Fn::GetAtt: [SubscribedChannelsTable, Arn]
            - Fn::GetAtt: [SmsMessagesTable, Arn]
  environment:
    PROCCESSED_NOTIFICATIONS_TABLE: ${param:proccessedNotificationsTableName}

functions:
  api:
    handler: src/http-api/app.lambda_handler
    timeout: 30
    memorySize: 128
    environment:
      DYNAMO_TABLE_SMS_MESSAGES: ${param:smsMessagesTableName}
      SQS_QUEUE_URL_INCOMING_SMS: ${construct:snowalerts-incoming-sms.queueUrl}
      TWILIO_AUTH_TOKEN: ${doppler:TWILIO_AUTH_TOKEN}
      INCOMING_SMS_URL: ${doppler:INCOMING_SMS_URL}
    events:
      - httpApi:
          path: /api/interactions
          method: POST
      - httpApi:
          path: /webhooks/incoming-sms
          method: POST
  incomingMessage:
    handler: src/incoming-message/app.lambda_handler
    # Event source in constructs section

  outgoingNotification:
    handler: src/outgoing-notification/app.lambda_handler
    # Event source in constructs section

resources:
  Resources:
    SubscribedChannelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: channel_id
            AttributeType: S
        KeySchema:
          - AttributeName: channel_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${param:subscribedChannelsTableName}

    SmsMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: message_sid
            AttributeType: S
          - AttributeName: received_at
            AttributeType: N
        KeySchema:
          - AttributeName: message_sid
            KeyType: HASH
          - AttributeName: received_at
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${param:smsMessagesTableName}

    ProccessedNotificationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: channel_id
            AttributeType: S
          - AttributeName: sent_at
            AttributeType: N
        KeySchema:
          - AttributeName: channel_id
            KeyType: HASH
          - AttributeName: sent_at
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${param:proccessedNotificationsTableName}

constructs:
  snowalerts-incoming-sms:
    type: queue
    worker: incomingMessage
  snowalerts-outgoing-notifications:
    type: queue
    worker: outgoingNotification
